language: php
php:
  - '5.6'

services:
  - docker

before_script:
  - composer install

script: 
  - vendor/bin/phpcs -s --colors --standard=rules.xml modules/
  - vendor/bin/phpmd modules/ text codesize
  - vendor/bin/phpcpd modules/
  - vendor/bin/phpdoccheck --directory=modules --exclude=bliskapaczka/tests
  - vendor/bin/phploc modules/
  - vendor/bin/phpunit --bootstrap modules/bliskapaczka/tests/bootstrap.php modules/bliskapaczka/tests/unit/
  - docker build -t bliskapaczkapl/prestashop .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push bliskapaczkapl/prestashop;
    fi