language: php
php:
  - '5.6'

env:
  - VENDOR_DIR=modules/bliskapaczka/vendor

services:
  - docker

before_script:
  - composer install

script: 
  - $VENDOR_DIR/bin/phpcs -s --colors --standard=rules.xml --ignore=modules/bliskapaczka/vendor/* modules/
  - $VENDOR_DIR/bin/phpmd modules/ text codesize --exclude modules/bliskapaczka/vendor
  - $VENDOR_DIR/bin/phpcpd --exclude vendor modules/
  - $VENDOR_DIR/bin/phpdoccheck --directory=modules --exclude=bliskapaczka/tests,bliskapaczka/vendor
  - $VENDOR_DIR/bin/phploc modules/
  - $VENDOR_DIR/bin/phpunit --bootstrap modules/bliskapaczka/tests/bootstrap.php modules/bliskapaczka/tests/unit/
  - docker build -t bliskapaczkapl/prestashop .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push bliskapaczkapl/prestashop;
    fi