version: "3"
services:
  prestashop:
    build:
      context: ./
      dockerfile: dev/docker/Dockerfile
    volumes:
      - "./modules/bliskapaczka:/var/www/html/modules/bliskapaczka"
      - "./composer.json:/var/www/html/composer.json"
